site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant

# Page tree
nav:
  - Home: index.md
  - Security:
    - Angriffe: Security\Angriffe\Angriffe.md
    - Authentication: Security\Authentication\Token.md
  - Workplace:
    - AVD: Workplace\AVD\AZ-140.md